<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container6K1tBJ7\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container6K1tBJ7/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container6K1tBJ7.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container6K1tBJ7\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \Container6K1tBJ7\srcApp_KernelDevDebugContainer([
    'container.build_hash' => '6K1tBJ7',
    'container.build_id' => '51101846',
    'container.build_time' => 1567207194,
], __DIR__.\DIRECTORY_SEPARATOR.'Container6K1tBJ7');
