<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerB4V7xhl\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerB4V7xhl/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerB4V7xhl.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerB4V7xhl\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerB4V7xhl\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'B4V7xhl',
    'container.build_id' => 'ee2123a3',
    'container.build_time' => 1558620006,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerB4V7xhl');
