<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerGkZViqD\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerGkZViqD/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerGkZViqD.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerGkZViqD\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerGkZViqD\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'GkZViqD',
    'container.build_id' => 'da573cb6',
    'container.build_time' => 1559583773,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerGkZViqD');
