<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerPzcQ2AW\srcApp_KernelProductionDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerPzcQ2AW/srcApp_KernelProductionDebugContainer.php') {
    touch(__DIR__.'/ContainerPzcQ2AW.legacy');

    return;
}

if (!\class_exists(srcApp_KernelProductionDebugContainer::class, false)) {
    \class_alias(\ContainerPzcQ2AW\srcApp_KernelProductionDebugContainer::class, srcApp_KernelProductionDebugContainer::class, false);
}

return new \ContainerPzcQ2AW\srcApp_KernelProductionDebugContainer([
    'container.build_hash' => 'PzcQ2AW',
    'container.build_id' => 'd11cd14a',
    'container.build_time' => 1555790120,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerPzcQ2AW');
